### ISSUE TITLE
是否要提供一个 kmem 关闭的版本

### ISSUE THREAD

**Issue by yank1** [DaoCloud-OpenSource/kubepatch#36]
kmem 是kube 的一个常见问题。是否我们可以提供一个 kmem 关闭的版本。

或者更智能一些，判断有 bug 的 OS，就使用 no kmem，没有 bug 的OS 使用普通的版本。

https://bugzilla.redhat.com/show_bug.cgi?id=1507149

**Comment by wzshiming** [comment]
https://github.com/opencontainers/runc/pull/2840

这个已经在 runc 1.0.0-rc94 修复, 可以把历史版本依赖的 runc 全部升级到 1.0.0

**Comment by wzshiming** [comment]
Fix by #50
